name: Stupid Workflow

on:
  push:
    branches:
      - main
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    env:
      HELLO: "WORLD"

    steps:
      - run: echo "Hi there!😻"

      - name: echo "Which is node?"
        run: |
          which node
          node --version

      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: List files in the repository
        run: |
          echo "${{ env.HELLO }}The repository ${{ github.repository }} contains the following files"
          tree
